
let dummyJSON = [
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PICTURE",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 3,
    title: "청춘예찬",
    content: "그들에게 생명을 불어 넣는 것은 따뜻한 봄바람이다. 풀밭에 속잎나고, 가지에 싹이 트고, 꽃 피고 새 우는 봄날의 천지는 얼마나 기쁘며, 얼마나 아름다우냐?",
    interestType: "READING",
    writer: {
      memberId: 1,
      nickname: "민태원",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "photo/reading_2_1.jpg",
      "photo/reading_1_1.jpg",
      "photo/reading_2.jpg",
    ],
  },
  {
    id: 1,
    title: "여름이였다",
    content: "나를 줄곧 떠나지 않는 갑갑함과 아릿함, 이 낯선 감정에 나는 망설이다가 슬픔이라는 아름답고도 묵직한 이름을 붙인다.",
    interestType: "PHOTO",
    writer: {
      memberId: 1,
      nickname: "프랑수아즈 사강",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "photo/photo_1.jpg",
      "photo/photo_2.jpg",
      "photo/photo_3.jpg",
      "photo/photo_4.jpg",
    ],
  },
  {
    id: 2,
    title: "롤 13시즌 챌린저 달성",
    content: "GCA Alpha 팀의 서포터로서 활동 중인 김용준 장학생은 ‘Saroo’ 이종원 코치님의 코칭을 받으며 아마추어 대회를 준비하고 있으며, 바텀 주도권을 활용한 팀 단위의 운영법",
    interestType: "GAMING",
    writer: {
      memberId: 1,
      nickname: "김용준",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:52.341923",
    modifiedDateTime: "2023-09-13T17:04:52.341866",
    viewCount: 0,
    likeCount: 2,
    fileURLs: ["photo/game_1.png",
    "photo/picture_1.jpg",
    "photo/picture_3.png"],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PHOTO",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 0,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
];
let dummyJSON2 = [
  {
    id: 2,
    title: "내방",
    content: "이쁘지?",
    interestType: "GAMING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:52.341923",
    modifiedDateTime: "2023-09-13T17:04:52.341866",
    viewCount: 0,
    likeCount: 2,
    fileURLs: ["background/basic_bg.png", "background/game_bg.png"],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "EXERCISE",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PICTURE",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "READING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 0,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 3,
    title: "내방",
    content: "이쁘지?",
    interestType: "PHOTO",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/basic_bg.png",
      "background/game_bg.png",
    ],
  },
];

export { dummyJSON, dummyJSON2 };
