let dummyJSON = [
  {
    id: 3,
    title: "내방",
    content: "이쁘지?",
    interestType: "PHOTO",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/basic_bg.png",
      "background/game_bg.png",
    ],
  },
  {
    id: 2,
    title: "내방",
    content: "이쁘지?",
    interestType: "READING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:52.341923",
    modifiedDateTime: "2023-09-13T17:04:52.341866",
    viewCount: 0,
    likeCount: 2,
    fileURLs: ["background/basic_bg.png", "background/game_bg.png"],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PAINTING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PAINTING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "READING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 0,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
];
let dummyJSON2 = [
  {
    id: 2,
    title: "내방",
    content: "이쁘지?",
    interestType: "READING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:52.341923",
    modifiedDateTime: "2023-09-13T17:04:52.341866",
    viewCount: 0,
    likeCount: 2,
    fileURLs: ["background/basic_bg.png", "background/game_bg.png"],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PAINTING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "PAINTING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 1,
    title: "내방",
    content: "이쁘지?",
    interestType: "READING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 0,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/read_bg.png",
    ],
  },
  {
    id: 3,
    title: "내방",
    content: "이쁘지?",
    interestType: "PAINTING",
    writer: {
      memberId: 1,
      nickname: "마팅",
      profileImgURL: null,
    },
    commentCount: 0,
    createdDateTime: "2023-09-13T17:04:51.669563",
    modifiedDateTime: "2023-09-13T17:04:51.668273",
    viewCount: 0,
    likeCount: 1,
    fileURLs: [
      "background/basic_bg.png",
      "background/game_bg.png",
      "background/basic_bg.png",
      "background/game_bg.png",
    ],
  },
];

export { dummyJSON, dummyJSON2 };
