/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/BlueDemon.gltf -o src/views/threejs/BlueDemon.js -r public 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function BlueDemon(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/BlueDemon.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='CharacterArmature'>
          <primitive object={nodes.Root} />
          <group name='BlueDemon'>
            <skinnedMesh
              name='Cube017'
              geometry={nodes.Cube017.geometry}
              material={materials.BlueDemon_Main}
              skeleton={nodes.Cube017.skeleton}
            />
            <skinnedMesh
              name='Cube017_1'
              geometry={nodes.Cube017_1.geometry}
              material={materials.BlueDemon_Secondary}
              skeleton={nodes.Cube017_1.skeleton}
            />
            <skinnedMesh
              name='Cube017_2'
              geometry={nodes.Cube017_2.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cube017_2.skeleton}
            />
            <skinnedMesh
              name='Cube017_3'
              geometry={nodes.Cube017_3.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cube017_3.skeleton}
            />
            <skinnedMesh
              name='Cube017_4'
              geometry={nodes.Cube017_4.geometry}
              material={materials.Wood}
              skeleton={nodes.Cube017_4.skeleton}
            />
            <skinnedMesh
              name='Cube017_5'
              geometry={nodes.Cube017_5.geometry}
              material={materials.Straps}
              skeleton={nodes.Cube017_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/BlueDemon.gltf");
